name: Continuous Development to VPS

on:
  push:
    branches:
      - main

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            source $NVM_DIR/nvm.sh
            cd /home/${{ secrets.USERNAME }}/iot-bridge-backend
            git checkout main
            git fetch origin main
            git reset --hard origin/main
            npm install
            npm run build
            pm2 restart iot-bridge-backend || pm2 start dist/main.js --name iot-bridge-backend
